providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["python -m pip install --break-system-packages --no-cache-dir -r backend/requirements.txt"]
