"""bar_tables_init

Revision ID: a601f714d2f2
Revises: 
Create Date: 2026-06-29 12:46:14.582740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a601f714d2f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pompes', 'actif',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="FALSE = pompe hors service (conservée pour l'historique).",
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_pompes_actif'), table_name='pompes', postgresql_where='(actif = true)')
    op.drop_constraint(op.f('fk_pompe_produit'), 'pompes', type_='foreignkey')
    op.create_foreign_key(None, 'pompes', 'produits', ['produit_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'pompes',
        existing_comment='Pompes/distributeurs physiques de la station.',
        schema=None
    )
    op.alter_column('produits', 'nom',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nom du produit : Gazoline, Diesel, Kérosène…',
               existing_nullable=False)
    op.alter_column('produits', 'prix_gallon',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment=None,
               existing_comment='Prix courant par gallon (gourdes). Utilisé comme valeur par défaut à la saisie.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('produits', 'actif',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="FALSE = produit archivé, masqué dans l'interface.",
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_table_comment(
        'produits',
        existing_comment='Types de carburant vendus à la station.',
        schema=None
    )
    op.alter_column('releves', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date du relevé.',
               existing_nullable=False)
    op.alter_column('releves', 'periode',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Période : 'Matin' ou 'Apres-midi'.",
               existing_nullable=False)
    op.alter_column('releves', 'prix_gallon',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment=None,
               existing_comment='Prix au gallon (gourdes) au moment du relevé. Peut différer du prix courant du produit.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('releves', 'metter_avant',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment=None,
               existing_comment='Lecture du compteur en DÉBUT de période (gallons cumulés).',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('releves', 'metter_apres',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment=None,
               existing_comment='Lecture du compteur en FIN de période. Doit être >= metter_avant.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_releves_date_desc'), table_name='releves')
    op.drop_constraint(op.f('fk_releve_pompe'), 'releves', type_='foreignkey')
    op.create_foreign_key(None, 'releves', 'pompes', ['pompe_id'], ['id'], ondelete='RESTRICT')
    op.drop_table_comment(
        'releves',
        existing_comment='Relevés de compteurs (deux par jour : Matin et Apres-midi).',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'releves',
        'Relevés de compteurs (deux par jour : Matin et Apres-midi).',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'releves', type_='foreignkey')
    op.create_foreign_key(op.f('fk_releve_pompe'), 'releves', 'pompes', ['pompe_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('idx_releves_date_desc'), 'releves', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('releves', 'metter_apres',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment='Lecture du compteur en FIN de période. Doit être >= metter_avant.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('releves', 'metter_avant',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment='Lecture du compteur en DÉBUT de période (gallons cumulés).',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('releves', 'prix_gallon',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Prix au gallon (gourdes) au moment du relevé. Peut différer du prix courant du produit.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('releves', 'periode',
               existing_type=sa.VARCHAR(length=20),
               comment="Période : 'Matin' ou 'Apres-midi'.",
               existing_nullable=False)
    op.alter_column('releves', 'date',
               existing_type=sa.DATE(),
               comment='Date du relevé.',
               existing_nullable=False)
    op.create_table_comment(
        'produits',
        'Types de carburant vendus à la station.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('produits', 'actif',
               existing_type=sa.BOOLEAN(),
               comment="FALSE = produit archivé, masqué dans l'interface.",
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('produits', 'prix_gallon',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Prix courant par gallon (gourdes). Utilisé comme valeur par défaut à la saisie.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('produits', 'nom',
               existing_type=sa.VARCHAR(length=100),
               comment='Nom du produit : Gazoline, Diesel, Kérosène…',
               existing_nullable=False)
    op.create_table_comment(
        'pompes',
        'Pompes/distributeurs physiques de la station.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'pompes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pompe_produit'), 'pompes', 'produits', ['produit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('idx_pompes_actif'), 'pompes', ['produit_id'], unique=False, postgresql_where='(actif = true)')
    op.alter_column('pompes', 'actif',
               existing_type=sa.BOOLEAN(),
               comment="FALSE = pompe hors service (conservée pour l'historique).",
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
